// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBesYnHMJNv6J4RvFraRf6em26SyoJ6JNU',
    appId: '1:627913551303:web:97a1c1d068bead177fbde2',
    messagingSenderId: '627913551303',
    projectId: 'payment-68c2d',
    authDomain: 'payment-68c2d.firebaseapp.com',
    storageBucket: 'payment-68c2d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa3kcezcUhHS5uGxXL28ndYg6JdyeE-kg',
    appId: '1:627913551303:android:fb586b957be66da77fbde2',
    messagingSenderId: '627913551303',
    projectId: 'payment-68c2d',
    storageBucket: 'payment-68c2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7X2VNrF72tAPHbGGCJCKbU7JomMramfA',
    appId: '1:627913551303:ios:9e21d7bf9b67a27f7fbde2',
    messagingSenderId: '627913551303',
    projectId: 'payment-68c2d',
    storageBucket: 'payment-68c2d.firebasestorage.app',
    iosBundleId: 'com.example.untitled3',
  );

}